[project]
name = "limesurvey"
revision = "1.0"
require_reason = false

[profiles.default]
LIMESURVEY_ADMIN_PASSWORD = { description = "LimeSurvey administrator account password" }
LIMESURVEY_DB_PASSWORD = { description = "MariaDB root password backing LimeSurvey" }
