[package]
name = "scroll-format"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
postcard = { workspace = true }
blake3 = { workspace = true }
hex = { workspace = true }
serde_json = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
