//! Systemd unit provider.
//!
//! We manage the *enablement and active state* of a unit, never the unit
//! file itself (those are File claims, or generated by the quadlet
//! generator). This keeps composition clean.
//!
//! Trait split: `capture` snapshots prior_active/prior_enabled read-only;
//! `mutate` runs systemctl. The reconciler journals capture before mutate
//! so a crashed mutate can be honestly reversed.

use anyhow::{anyhow, bail, Context, Result};
use async_trait::async_trait;
use golem_types::{Backup, Capture, CaptureError, ClaimSpec, Health, Scope, SystemdUnitSpec};
use tokio::process::Command;

use super::{Observation, Provider};

pub struct SystemdUnitProvider;

fn spec_of(spec: &ClaimSpec) -> &SystemdUnitSpec {
    match spec {
        ClaimSpec::SystemdUnit(s) => s,
        _ => unreachable!("SystemdUnitProvider dispatched on non-unit spec"),
    }
}

fn systemctl_args(scope: Scope) -> Vec<&'static str> {
    match scope {
        Scope::System => vec![],
        Scope::User   => vec!["--user"],
    }
}

async fn systemctl(scope: Scope, args: &[&str]) -> Result<()> {
    let mut cmd = Command::new("systemctl");
    for a in systemctl_args(scope) { cmd.arg(a); }
    cmd.args(args);
    let status = cmd.status().await.context("spawn systemctl")?;
    if !status.success() { bail!("systemctl {args:?} failed: {status}"); }
    Ok(())
}

/// Returns (active, enabled). `enabled` is true for "enabled" *or* "static"
/// (static units can't be disabled; we treat them as always-on).
///
/// We use `--property=…` with explicit per-property invocations and parse
/// `key=value` form, which is robust to ordering and presence-vs-absence
/// changes across systemd versions. (The previous line-based parse would
/// silently misalign if any property's value was multi-line.)
async fn systemctl_show(scope: Scope, unit: &str) -> Result<Option<(bool, bool)>> {
    let mut cmd = Command::new("systemctl");
    for a in systemctl_args(scope) { cmd.arg(a); }
    cmd.args(["show", "-p", "ActiveState", "-p", "UnitFileState", "-p", "LoadState", unit]);
    let out = cmd.output().await?;
    if !out.status.success() { return Ok(None); }
    let s = String::from_utf8_lossy(&out.stdout);

    let mut active = "";
    let mut enabled = "";
    let mut loaded = "";
    for line in s.lines() {
        if let Some((k, v)) = line.split_once('=') {
            match k {
                "ActiveState"   => active  = v.trim(),
                "UnitFileState" => enabled = v.trim(),
                "LoadState"     => loaded  = v.trim(),
                _ => {}
            }
        }
    }
    if loaded == "not-found" { return Ok(None); }
    let is_active  = active == "active" || active == "activating";
    let is_enabled = matches!(enabled, "enabled" | "static" | "enabled-runtime" | "generated");
    Ok(Some((is_active, is_enabled)))
}

/// Call systemctl daemon-reload. Should be debounced by the reconciler —
/// if ten quadlet files change in one tick, we want one reload.
pub async fn daemon_reload(scope: Scope) -> Result<()> {
    systemctl(scope, &["daemon-reload"]).await
}

#[async_trait]
impl Provider for SystemdUnitProvider {
    async fn observe(&self, spec: &ClaimSpec) -> Result<Observation> {
        let s = spec_of(spec);
        Ok(match systemctl_show(s.scope, &s.name).await? {
            Some(_) => Observation::Present,
            None    => Observation::Absent,
        })
    }

    async fn matches(&self, spec: &ClaimSpec) -> Result<bool> {
        let s = spec_of(spec);
        match systemctl_show(s.scope, &s.name).await? {
            None => Ok(false),
            Some((is_active, is_enabled)) => Ok(is_active == s.active && is_enabled == s.enable),
        }
    }

    async fn capture(&self, spec: &ClaimSpec) -> Result<Capture, CaptureError> {
        let s = spec_of(spec);
        match systemctl_show(s.scope, &s.name)
            .await
            .map_err(|e| CaptureError::Other(anyhow!(e)))?
        {
            Some((act, en)) => Ok(Capture {
                preexisting: true,
                backup: Backup {
                    existed:       true,
                    prior_active:  Some(act),
                    prior_enabled: Some(en),
                    ..Backup::default()
                },
            }),
            None => Ok(Capture {
                preexisting: false,
                backup: Backup { existed: false, ..Backup::default() },
            }),
        }
    }

    async fn mutate(&self, spec: &ClaimSpec, _capture: &Capture) -> Result<()> {
        let s = spec_of(spec);
        if s.enable { systemctl(s.scope, &["enable",  &s.name]).await?; }
        else        { systemctl(s.scope, &["disable", &s.name]).await.ok(); }
        if s.active { systemctl(s.scope, &["start",   &s.name]).await?; }
        else        { systemctl(s.scope, &["stop",    &s.name]).await.ok(); }
        Ok(())
    }

    async fn unmutate(&self, spec: &ClaimSpec, capture: &Capture) -> Result<()> {
        let s = spec_of(spec);
        if !capture.preexisting {
            // We caused this unit to be enabled/active. Stop and disable.
            systemctl(s.scope, &["stop",    &s.name]).await.ok();
            systemctl(s.scope, &["disable", &s.name]).await.ok();
            return Ok(());
        }

        // Restore prior state precisely.
        match (capture.backup.prior_active, capture.backup.prior_enabled) {
            (Some(was_active), Some(was_enabled)) => {
                if was_enabled { systemctl(s.scope, &["enable",  &s.name]).await.ok(); }
                else           { systemctl(s.scope, &["disable", &s.name]).await.ok(); }
                if was_active  { systemctl(s.scope, &["start",   &s.name]).await.ok(); }
                else           { systemctl(s.scope, &["stop",    &s.name]).await.ok(); }
            }
            _ => {
                systemctl(s.scope, &["stop",    &s.name]).await.ok();
                systemctl(s.scope, &["disable", &s.name]).await.ok();
            }
        }
        Ok(())
    }

    async fn check(&self, spec: &ClaimSpec) -> Result<Health> {
        if self.matches(spec).await? {
            Ok(Health::Healthy)
        } else {
            Ok(Health::Degraded("unit not in desired state".into()))
        }
    }
}

/// Restart a unit (used by the handler machinery). Not part of Provider
/// because handlers are keyed on unit *name*, not ClaimId.
pub async fn restart_unit(scope: Scope, unit: &str) -> Result<()> {
    systemctl(scope, &["restart", unit]).await
}
