[package]
name = "emet"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "emetc"

[dependencies]
ariadne = "0.4.1"
chumsky = "0.10"
clap = { workspace = true }
secretspec = { workspace = true }
scroll-format = { workspace = true, features = ["secrets"] }
serde = { workspace = true }
serde_json = { workspace = true }
workspace-hack = { version = "0.1", path = "../../libs/workspace-hack" }

[dev-dependencies]
tempfile = { workspace = true }

[[bin]]
name = "emetc"
path = "src/main.rs"

[lib]
name = "emet"
path = "src/lib.rs"
