from __future__ import annotations

NAME = "golem"
# NOTE: TITLE is both the title slide's headline and the combined deck's
# Excalidraw frame name, and a full sentence is unreadable in a frame list.
# Import it rather than retyping it so the two stay one literal.
TITLE = "golem"

SLIDE_MODULE_NAMES: tuple[str, ...] = (
    "s01_title",
    "s02_what_you_buy",
    "s03_what_you_configure",
    "s04_fleet_machines",
    "s05_fleet_basics",
    "s06_fleet_by_hand",
    "s07_fleet_generated_config",
    "s08_fleet_now",
    "s09_december_discovery",
    "s10_december_placement",
    "s11_playbook_a_file",
    "s12_playbook_a_line",
    "s13_playbook_more_files",
    "s14_playbook_a_workload",
    "s15_what_do_we_undo",
    "s16_the_goals",
    "s17_scrolls_compiled",
    "s18_scrolls_dispatched",
    "s19_fleet_assembling",
    "s20_fleet_golem",
    "s21_moving_a_service",
    "s22_what_golem_is",
    "s23_requirement_and_property",
    "s24_the_pipeline",
    "s25_the_diff",
    "s26_apply_and_undo",
    "s27_the_scroll_tree",
    "s28_the_four_glyphs",
    "s29_golemctl_verbs",
    "s30_golemd_routes",
    "s31_plan_against_host",
    "s32_outcome_based_development",
    "s33_current_status",
    "s34_longer_term_goals",
    "s35_adversarial_conditions",
    "s36_grading_goals_one_to_three",
    "s37_grading_goals_four_and_five",
    "s38_looking_for_feedback",
    "s39_where_lichess_sits",
    "s40_where_lichess_sits_with_portainer",
    "s41_lichess_stack",
    "s42_orchestration",
    "s43_bought_orchestration",
    "s44_ansible",
    "s45_december_owners",
    "s46_december_moving_a_service",
    "s47_where_it_broke",
)
