from __future__ import annotations

NAME = "golem"
# NOTE: TITLE is both the title slide's headline and the combined deck's
# Excalidraw frame name, and a full sentence is unreadable in a frame list.
# Import it rather than retyping it so the two stay one literal.
TITLE = "golem"

SLIDE_MODULE_NAMES: tuple[str, ...] = (
    "s01_title",
    "s02_what_you_buy",
    "s03_what_you_configure",
    "s04_fleet_machines",
    "s05_fleet_basics",
    "s06_fleet_by_hand",
    "s07_fleet_generated_config",
    "s08_fleet_now",
    "s09_december_discovery",
    "s10_december_placement",
    "s11_playbook_a_file",
    "s12_playbook_a_line",
    "s13_playbook_more_files",
    "s14_playbook_a_workload",
    "s15_what_do_we_undo",
    "s16_the_goals",
    "s17_scrolls_compiled",
    "s18_scrolls_dispatched",
    "s19_plan_the_first_apply",
    "s20_after_the_first_apply",
    "s21_plan_one_host_changes",
    "s22_emptying_a_host",
    "s23_fleet_assembling",
    "s24_fleet_golem",
    "s26_moving_a_service",
    "s27_what_golem_is",
    "s28_requirement_and_property",
    "s29_plan_against_host",
    "s30_outcome_based_development",
    "s31_current_status",
    "s32_longer_term_goals",
    "s33_adversarial_conditions",
    "s34_grading_goals_one_to_three",
    "s35_grading_goals_four_and_five",
    "s36_looking_for_feedback",
    "s38_the_pipeline",
    "s39_the_diff",
    "s40_apply_and_undo",
    "s41_the_scroll_tree",
    "s42_the_four_glyphs",
    "s43_golemctl_verbs",
    "s44_golemd_routes",
    "s45_where_lichess_sits",
    "s46_where_lichess_sits_with_portainer",
    "s47_lichess_stack",
    "s48_orchestration",
    "s49_bought_orchestration",
    "s50_ansible",
    "s51_december_owners",
    "s52_december_moving_a_service",
    "s53_where_it_broke",
)
