from __future__ import annotations

NAME = "golem"
TITLE = "golem — one program, written down as state"

SLIDE_MODULE_NAMES: tuple[str, ...] = (
    "s01_title",
    "s02_what_you_buy",
    "s03_what_you_configure",
    "s04_fleet_machines",
    "s05_fleet_basics",
    "s06_fleet_by_hand",
    "s07_fleet_generated_config",
    "s08_fleet_now",
    "s09_december_discovery",
    "s10_december_placement",
    "s17_scrolls_compiled",
    "s18_scrolls_dispatched",
    "s19_fleet_assembling",
    "s20_fleet_golem",
    "s21_moving_a_service",
    "s22_what_golem_is",
    "s23_requirement_and_property",
    "s24_the_pipeline",
    "s25_the_diff",
    "s26_apply_and_undo",
    "s27_the_scroll_tree",
    "s28_the_four_glyphs",
    "s29_golemctl_verbs",
    "s30_golemd_routes",
    "s31_plan_against_host",
    "s38_where_lichess_sits",
    "s39_where_lichess_sits_with_portainer",
    "s40_lichess_stack",
    "s41_orchestration",
    "s42_bought_orchestration",
    "s43_ansible",
    "s44_december_owners",
    "s45_december_moving_a_service",
    "s46_where_it_broke",
)
