[package]
name    = "golemctl"
version.workspace = true
edition.workspace = true

[dependencies]
golem-types  = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
tokio        = { workspace = true }
anyhow       = { workspace = true }
thiserror    = { workspace = true }
tracing      = { workspace = true }
tracing-subscriber = { workspace = true }
chrono       = { workspace = true }
hex          = { workspace = true }
ed25519-dalek = { workspace = true, features = ["rand_core"] }
clap         = { workspace = true }
reqwest      = { workspace = true }
rand_core    = { version = "0.6", features = ["std"] }
nickel-lang  = "2.0"
